package simulator.entity;

public enum RelativeDirection {
  NONE,
  FRONT,
  FRONT_RIGHT,
  FRONT_LEFT,
  FRONT_SLIGHT_RIGHT,
  FRONT_SLIGHT_LEFT,
  BACK,
  BACK_RIGHT,
  BACK_LEFT,
  BACK_SLIGHT_RIGHT,
  BACK_SLIGHT_LEFT,
  CENTER_RIGHT,
  CENTER_LEFT
}
